flag-only-for-admin:
  variations:
    is-admin: true
    not-admin: false
  defaultRule:
    variation: not-admin
  targeting:
    - name: check admin
      query: key eq "d45e303a-38c2-11ed-a261-0242ac12002"
      variation: is-admin
